"""
/v1/ocean/saliency endpoint.

Returns the binary float32 data for the model's computed saliency masks,
indicating the spatial regions that most influenced the generated predictions.
Matches the binary streaming pattern of /field.

NOTE: Saliency maps are only available if the inference worker writes
``saliency_{variable}`` arrays to the Zarr store.  If missing, this
endpoint returns 404 (not 500).
"""

from __future__ import annotations

import asyncio

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response

from ...infrastructure.dependencies import get_zarr_resolver
from ...infrastructure.zarr.resolver import ZarrStoreResolver
from ..constants import VALID_VARIABLE_NAMES

router = APIRouter(tags=["Ocean — Saliency"])


@router.get("/saliency")
async def get_saliency(
    variable: str,
    week: str | None = None,
    depth: float | None = None,
    resolver: ZarrStoreResolver = Depends(get_zarr_resolver),
) -> Response:
    """Return raw float32 binary for the requested saliency variable.

    - ``depth`` omitted → full 3D volume
    - ``depth`` provided → 2D slice

    Returns 404 if saliency maps have not been generated for this variable.
    """
    if variable not in VALID_VARIABLE_NAMES:
        raise HTTPException(
            status_code=422,
            detail=f"Unknown variable '{variable}'. Valid: {sorted(VALID_VARIABLE_NAMES)}",
        )

    try:
        store = await resolver.get_store(week=week)
    except (FileNotFoundError, RuntimeError) as exc:
        raise HTTPException(status_code=503, detail=str(exc))

    saliency_var = f"saliency_{variable}"

    if saliency_var not in store:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Saliency map '{saliency_var}' not found in store. "
                "Saliency maps must be generated by the inference worker."
            ),
        )

    def _extract():
        da = store[saliency_var]
        if depth is not None:
            da = da.sel(depth=depth, method="nearest")
            buf = da.values.astype("float32").tobytes()
            shape_header = f"{da.shape[0]},{da.shape[1]}"
        else:
            buf = da.values.astype("float32").tobytes()
            shape_header = ",".join(str(s) for s in da.shape)
        return buf, shape_header

    try:
        buf, shape_header = await asyncio.to_thread(_extract)
    except (KeyError, ValueError) as exc:
        raise HTTPException(status_code=422, detail=f"Data extraction failed: {exc}")

    return Response(
        content=buf,
        media_type="application/octet-stream",
        headers={
            "X-Shape": shape_header,
            "X-Variable": saliency_var,
            "X-Model-Version": store.attrs.get("model_version", "unknown"),
            "X-Week": store.attrs.get("week_label", "unknown"),
        },
    )
